# Generated by Django 4.0.4 on 2022-04-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deal', models.IntegerField()),
                ('name_deal', models.CharField(max_length=100)),
                ('description_deal', models.CharField(max_length=1000, null=True)),
                ('date_deal', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.IntegerField()),
                ('first_id', models.IntegerField(null=True)),
                ('second_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_preference', models.CharField(max_length=10)),
                ('notification_type', models.IntegerField()),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
